language: c
services: docker
os: linux
env:
    - TARGET=docker-linux-x64 MODE=Debug
    - TARGET=docker-linux-x64 MODE=Release
    # - TARGET=docker-windows-x64
    # - TARGET=docker-android-arm64
script:
    - make $TARGET

