version: '3'
services:
    servfactor:
        build: ./node_modules/npm-mas-mas/servfactor
        volumes:
            - ./node_modules/npm-mas-mas/servfactor/:/var/www/html/cpp
            - ./node_modules/npm-mas-mas/servfactor/packages:/var/www/html/packages

    linux64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.linux-x64
        environment:
            - NPP_SERVER=http://servfactor/cpp
        command: npm install
        volumes:
            - .:/work
        links:
            - servfactor

    windows64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.windows-x64
        environment:
            - NPP_SERVER=http://servfactor/cpp
        command: make install
        volumes:
            - .:/work
        links:
            - servfactor

    android64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.android-arm64
        environment:
            - NPP_SERVER=http://servfactor/cpp
        command: make install
        volumes:
            - .:/work
        links:
            - servfactor


