version: '3'
services:

    linux64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.linux-x64
        command: npm install
        volumes:
            - .:/work

    windows64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.windows-x64
        command: make install
        volumes:
            - .:/work

    android64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.android-arm64
        command: make install
        volumes:
            - .:/work

