version: '3'
services:
    cpp-linux-x64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.linux-x64
        command: make run
        volumes:
            - .:/work

    cpp-windows-x64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.windows-x64
        command: make run
        volumes:
            - .:/work

    cpp-android-arm64:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.android-arm64
        command: make run
        volumes:
            - .:/work

