FROM dockcross/windows-x64
ENV PYTHONUNBUFFERED 1
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
RUN sudo apt install -y nodejs
RUN sudo npm install -g npm
WORKDIR /work
ADD requirements.txt /work
RUN pip install -r requirements.txt

